$(function(){
  const $win=$(window), $body=$('body');
  // Intro: count-up and red progress sweep.
  let progress=0; const $loader=$('#loader');
  const loadTimer=setInterval(()=>{progress=Math.min(100,progress+Math.ceil(Math.random()*4));$('#loadPercent').text(String(progress).padStart(2,'0')+'%');$('.load-track i').css('width',progress+'%');if(progress>=100){clearInterval(loadTimer);setTimeout(()=>{$loader.addClass('done');$body.removeClass('loading');setTimeout(()=>{$loader.remove();},1100);},300);}},42);
  $body.addClass('loading');

  // Full-screen menu.
  $('.menu-toggle').on('click',function(){const open=!$(this).hasClass('active');$(this).toggleClass('active',open).attr('aria-label',open?'Close navigation':'Open navigation');$('.menu-overlay').toggleClass('open',open);$body.toggleClass('menu-open',open);});
  $('.menu-overlay a').on('click',function(){$('.menu-toggle').removeClass('active').attr('aria-label','Open navigation');$('.menu-overlay').removeClass('open');$body.removeClass('menu-open');});

  // Smooth-ish section choreography, scroll progress and parallax.
  let ticking=false;
  function updateScroll(){const y=$win.scrollTop(), h=$win.height();$('.hero-image').css('transform',`scale(${1.12+Math.min(y/5000,.13)}) translateY(${y*.08}px)`);$('.scroll-meter i').css('width',Math.min(100,y/Math.max(1,document.documentElement.scrollHeight-h)*100)+'%');$('.future-image').css('transform',`scale(${1.1+Math.min(Math.max(y-$('.future').offset().top+h,0)/5000,.12)}) translateY(${Math.max(0,y-$('.future').offset().top)*.035}px)`);ticking=false;}
  $win.on('scroll',function(){if(!ticking){requestAnimationFrame(updateScroll);ticking=true;}});updateScroll();

  // Scroll reveals.
  const revealTargets='.purpose-copy,.orb-stage,.manifesto-inner,.worlds-heading,.world-card,.numbers-intro,.stat,.future-copy,.people-title,.people-art,.finale-copy';$(revealTargets).addClass('reveal');
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');if(entry.target.classList.contains('stat'))animateCounter(entry.target);observer.unobserve(entry.target);}}),{threshold:.18});document.querySelectorAll(revealTargets).forEach(el=>observer.observe(el));
  function animateCounter(el){const n=el.querySelector('.count');if(!n||n.dataset.done)return;n.dataset.done='1';const end=+n.dataset.count,start=performance.now(),duration=1600;function frame(now){const t=Math.min(1,(now-start)/duration);n.textContent=Math.round(end*(1-Math.pow(1-t,3)));if(t<1)requestAnimationFrame(frame);}requestAnimationFrame(frame);}

  // Interactive orbit follows pointer and reacts to scroll position.
  const orb=document.getElementById('orbStage');if(orb){orb.addEventListener('pointermove',e=>{const r=orb.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;orb.style.setProperty('--mx',x);orb.style.setProperty('--my',y);orb.querySelectorAll('.orbit').forEach((ring,i)=>{ring.style.marginLeft=(x*(i+1)*24)+'px';ring.style.marginTop=(y*(i+1)*18)+'px';});});orb.addEventListener('pointerleave',()=>orb.querySelectorAll('.orbit').forEach(r=>{r.style.marginLeft='0';r.style.marginTop='0';}));}

  // Drag-to-scroll horizontal worlds rail and arrow controls.
  const rail=document.getElementById('worldRail');let down=false,startX=0,scrollStart=0,moved=false;
  if(rail){rail.addEventListener('pointerdown',e=>{down=true;moved=false;startX=e.clientX;scrollStart=rail.scrollLeft;rail.classList.add('dragging');});window.addEventListener('pointerup',()=>{down=false;rail.classList.remove('dragging');});rail.addEventListener('pointermove',e=>{if(!down)return;const dx=e.clientX-startX;if(Math.abs(dx)>4)moved=true;rail.scrollLeft=scrollStart-dx;});rail.addEventListener('click',e=>{if(moved){e.preventDefault();e.stopPropagation();}},true);const cards=()=>rail.querySelectorAll('.world-card');function moveRail(dir){const c=cards()[0];if(c)rail.scrollBy({left:dir*(c.getBoundingClientRect().width+16),behavior:'smooth'});}$('.rail-next').on('click',()=>moveRail(1));$('.rail-prev').on('click',()=>moveRail(-1));rail.addEventListener('scroll',()=>{const c=cards()[0];if(c){const index=Math.min(cards().length,Math.max(1,Math.round(rail.scrollLeft/(c.getBoundingClientRect().width+16))+1));$('.rail-count').html(String(index).padStart(2,'0')+' <i>/</i> '+String(cards().length).padStart(2,'0'));}},{passive:true});}

  // Custom pointer on desktop.
  const cursor=document.querySelector('.cursor'),dot=document.querySelector('.cursor-dot');let cx=innerWidth/2,cy=innerHeight/2,dx=cx,dy=cy;window.addEventListener('pointermove',e=>{dx=e.clientX;dy=e.clientY;cursor.style.opacity=1;dot.style.opacity=1;});function cursorFrame(){cx+=(dx-cx)*.18;cy+=(dy-cy)*.18;cursor.style.left=cx+'px';cursor.style.top=cy+'px';dot.style.left=dx+'px';dot.style.top=dy+'px';requestAnimationFrame(cursorFrame);}if(matchMedia('(pointer:fine)').matches)cursorFrame();$('a,button,.world-card,.orb-stage').on('pointerenter',()=>cursor.classList.add('hover')).on('pointerleave',()=>cursor.classList.remove('hover'));

  // Hero canvas: luminous points respond to the pointer, without external 3D dependencies.
  function particleField(canvasId,finalMode=false){const canvas=document.getElementById(canvasId);if(!canvas)return;const ctx=canvas.getContext('2d');let w=0,h=0,particles=[],mouse={x:-1000,y:-1000};function resize(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);w=rect.width;h=rect.height;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);const count=Math.min(170,Math.floor(w*h/(finalMode?8000:9000)));particles=Array.from({length:count},()=>({x:Math.random()*w,y:Math.random()*h,z:.3+Math.random()*.7,r:.5+Math.random()*1.5,vx:(Math.random()-.5)*.24,vy:(Math.random()-.5)*.24,phase:Math.random()*6.28}));}window.addEventListener('resize',resize);canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();mouse.x=e.clientX-r.left;mouse.y=e.clientY-r.top;});canvas.addEventListener('pointerleave',()=>{mouse.x=-1000;mouse.y=-1000;});function draw(t){ctx.clearRect(0,0,w,h);for(let i=0;i<particles.length;i++){const p=particles[i];p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;const mx=p.x-mouse.x,my=p.y-mouse.y,dist=Math.hypot(mx,my);if(dist<115&&dist>0){p.x+=mx/dist*1.15;p.y+=my/dist*1.15;}const alpha=.18+.5*(.5+.5*Math.sin(t*.001+p.phase));ctx.beginPath();ctx.arc(p.x,p.y,p.r*p.z,0,Math.PI*2);ctx.fillStyle=finalMode?`rgba(255,255,255,${alpha*.45})`:`rgba(238,230,225,${alpha})`;ctx.fill();if(!finalMode){for(let j=i+1;j<particles.length;j++){const q=particles[j],dd=Math.hypot(p.x-q.x,p.y-q.y);if(dd<85){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.strokeStyle=`rgba(227,24,55,${(1-dd/85)*.22})`;ctx.lineWidth=.6;ctx.stroke();}}}}requestAnimationFrame(draw);}resize();requestAnimationFrame(draw);}
  particleField('particleCanvas');particleField('finalCanvas',true);

  // Mouse tilt for image-led human story.
  const art=document.getElementById('peopleArt');if(art&&matchMedia('(pointer:fine)').matches){art.addEventListener('pointermove',e=>{const r=art.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;art.querySelector('.people-photo').style.transform=`scale(.98) translate(${x*-12}px,${y*-12}px)`;art.querySelector('.people-sticker').style.transform=`translate(${x*10}px,${y*10}px) rotate(${8+x*5}deg)`;});art.addEventListener('pointerleave',()=>{art.querySelector('.people-photo').style.transform='';art.querySelector('.people-sticker').style.transform='';});}
});
